- type: job
  id: AtmosphericTechnician
  name: job-name-atmostech
  description: job-description-atmostech
  playTimeTracker: JobAtmosphericTechnician
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 9000
  startingGear: AtmosphericTechnicianGear
  icon: "AtmosphericTechnician"
  supervisors: job-supervisors-ce
  antagAdvantage: 10
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics
  minBankBalance: 300
  maxBankBalance: 500
  wageDepartment: Engineering
  wage: 100

- type: startingGear
  id: AtmosphericTechnicianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAtmos
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesColorWhite
    eyes: ClothingEyesGlassesMeson
    id: AtmosPDA
    belt: ClothingBeltUtilityFilled
    ears: ClothingHeadsetEngineering
  innerclothingskirt: ClothingUniformJumpskirtAtmos
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
